
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/up_counter 

module up_counter(clk, rst, en, count);
  input clk, rst, en;
  output [7:0] count;
  wire clk, rst, en;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_33;
  DFFSNQ_X1 \count_reg[7] (.SN (1'b1), .CLK (clk), .D (n_33), .Q
       (count[7]));
  INV_X1 g421(.I (n_31), .ZN (n_33));
  DFFSNQ_X1 \count_reg[5] (.SN (1'b1), .CLK (clk), .D (n_30), .Q
       (count[5]));
  AOI22_X1 g422(.A1 (n_23), .A2 (n_27), .B1 (count[7]), .B2 (n_26), .ZN
       (n_31));
  DFFSNQ_X1 \count_reg[6] (.SN (1'b1), .CLK (clk), .D (n_29), .Q
       (count[6]));
  DFFSNQ_X1 \count_reg[3] (.SN (1'b1), .CLK (clk), .D (n_25), .Q
       (count[3]));
  INV_X1 g425(.I (n_28), .ZN (n_30));
  INV_X1 g430(.I (n_24), .ZN (n_29));
  DFFSNQ_X1 \count_reg[4] (.SN (1'b1), .CLK (clk), .D (n_21), .Q
       (count[4]));
  AOI22_X1 g426(.A1 (n_20), .A2 (n_27), .B1 (count[5]), .B2 (n_26), .ZN
       (n_28));
  INV_X1 g428(.I (n_22), .ZN (n_25));
  AOI22_X1 g431(.A1 (n_17), .A2 (n_27), .B1 (count[6]), .B2 (n_26), .ZN
       (n_24));
  XOR2_X1 g432(.A1 (n_16), .A2 (count[7]), .Z (n_23));
  AOI22_X1 g429(.A1 (n_14), .A2 (n_27), .B1 (count[3]), .B2 (n_26), .ZN
       (n_22));
  DFFSNQ_X1 \count_reg[2] (.SN (1'b1), .CLK (clk), .D (n_18), .Q
       (count[2]));
  INV_X1 g434(.I (n_19), .ZN (n_21));
  XOR2_X1 g436(.A1 (n_12), .A2 (count[5]), .Z (n_20));
  AOI22_X1 g435(.A1 (n_13), .A2 (n_27), .B1 (count[4]), .B2 (n_26), .ZN
       (n_19));
  INV_X1 g437(.I (n_15), .ZN (n_18));
  HA_X1 g440(.A (count[6]), .B (n_10), .CO (n_16), .S (n_17));
  AOI22_X1 g438(.A1 (n_8), .A2 (n_27), .B1 (count[2]), .B2 (n_26), .ZN
       (n_15));
  XOR2_X1 g439(.A1 (n_7), .A2 (count[3]), .Z (n_14));
  DFFSNQ_X1 \count_reg[1] (.SN (1'b1), .CLK (clk), .D (n_11), .Q
       (count[1]));
  HA_X1 g442(.A (count[4]), .B (n_9), .CO (n_12), .S (n_13));
  NOR2_X1 g443(.A1 (n_6), .A2 (rst), .ZN (n_11));
  DFFSNQ_X1 \count_reg[0] (.SN (1'b1), .CLK (clk), .D (n_4), .Q
       (count[0]));
  AND3_X1 g445(.A1 (n_9), .A2 (count[5]), .A3 (count[4]), .Z (n_10));
  HA_X1 g444(.A (count[2]), .B (n_5), .CO (n_7), .S (n_8));
  AOI22_X1 g446(.A1 (n_1), .A2 (en), .B1 (count[1]), .B2 (n_2), .ZN
       (n_6));
  AND3_X1 g448(.A1 (n_5), .A2 (count[3]), .A3 (count[2]), .Z (n_9));
  NOR2_X1 g449(.A1 (n_3), .A2 (rst), .ZN (n_4));
  AOI22_X1 g451(.A1 (count[0]), .A2 (n_2), .B1 (n_0), .B2 (en), .ZN
       (n_3));
  HA_X1 g450(.A (count[0]), .B (count[1]), .CO (n_5), .S (n_1));
  NOR2_X1 g452(.A1 (n_2), .A2 (rst), .ZN (n_27));
  NOR2_X1 g453(.A1 (rst), .A2 (en), .ZN (n_26));
  INV_X1 g455(.I (en), .ZN (n_2));
  INV_X1 g454(.I (count[0]), .ZN (n_0));
endmodule

