
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/up_counter 

module up_counter(clk, rst, en, count);
  input clk, rst, en;
  output [7:0] count;
  wire clk, rst, en;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29;
  DFFQXL \count_reg[7] (.CK (clk), .D (n_29), .Q (count[7]));
  DFFHQX1 \count_reg[6] (.CK (clk), .D (n_28), .Q (count[6]));
  NOR2X1 g133(.A (rst), .B (n_27), .Y (n_29));
  NOR2X1 g136(.A (rst), .B (n_25), .Y (n_28));
  DFFHQX1 \count_reg[5] (.CK (clk), .D (n_26), .Q (count[5]));
  AOI22X1 g135(.A0 (en), .A1 (n_23), .B0 (n_24), .B1 (count[7]), .Y
       (n_27));
  NOR2X1 g140(.A (rst), .B (n_22), .Y (n_26));
  DFFHQX1 \count_reg[4] (.CK (clk), .D (n_21), .Q (count[4]));
  AOI22X1 g138(.A0 (en), .A1 (n_20), .B0 (n_24), .B1 (count[6]), .Y
       (n_25));
  XNOR2X1 g137(.A (count[7]), .B (n_17), .Y (n_23));
  DFFHQX1 \count_reg[3] (.CK (clk), .D (n_18), .Q (count[3]));
  AOI22X1 g142(.A0 (en), .A1 (n_15), .B0 (n_24), .B1 (count[5]), .Y
       (n_22));
  NOR2X1 g145(.A (rst), .B (n_19), .Y (n_21));
  XNOR2X1 g141(.A (count[6]), .B (n_16), .Y (n_20));
  AOI22X1 g147(.A0 (en), .A1 (n_11), .B0 (n_24), .B1 (count[4]), .Y
       (n_19));
  NOR2X1 g150(.A (rst), .B (n_13), .Y (n_18));
  DFFHQX1 \count_reg[2] (.CK (clk), .D (n_12), .Q (count[2]));
  NAND2BX1 g144(.AN (n_16), .B (count[6]), .Y (n_17));
  XNOR2X1 g146(.A (count[5]), .B (n_14), .Y (n_15));
  NAND2BX1 g149(.AN (n_14), .B (count[5]), .Y (n_16));
  AOI22X1 g152(.A0 (en), .A1 (n_7), .B0 (n_24), .B1 (count[3]), .Y
       (n_13));
  NOR2X1 g155(.A (rst), .B (n_9), .Y (n_12));
  DFFHQX1 \count_reg[1] (.CK (clk), .D (n_8), .Q (count[1]));
  XNOR2X1 g151(.A (count[4]), .B (n_10), .Y (n_11));
  DFFHQX1 \count_reg[0] (.CK (clk), .D (n_5), .Q (count[0]));
  NAND2BX1 g154(.AN (n_10), .B (count[4]), .Y (n_14));
  AOI22X1 g157(.A0 (en), .A1 (n_3), .B0 (n_24), .B1 (count[2]), .Y
       (n_9));
  NOR2X1 g160(.A (rst), .B (n_6), .Y (n_8));
  XNOR2X1 g156(.A (count[3]), .B (n_4), .Y (n_7));
  AOI22X1 g162(.A0 (en), .A1 (n_0), .B0 (n_24), .B1 (count[1]), .Y
       (n_6));
  NOR2X1 g165(.A (rst), .B (n_1), .Y (n_5));
  NAND2BX1 g159(.AN (n_4), .B (count[3]), .Y (n_10));
  XNOR2X1 g161(.A (count[2]), .B (n_2), .Y (n_3));
  NAND2BX1 g164(.AN (n_2), .B (count[2]), .Y (n_4));
  MX2XL g166(.A (n_24), .B (en), .S0 (count[0]), .Y (n_1));
  XOR2XL g167(.A (count[1]), .B (count[0]), .Y (n_0));
  NAND2X1 g168(.A (count[1]), .B (count[0]), .Y (n_2));
  INVXL g169(.A (en), .Y (n_24));
endmodule

